version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:3.7
    ports:
      - "127.0.0.1:4567:4566"
      - "127.0.0.1:4572:4571"
      - "127.0.0.1:${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=eu-west-1
      - DATA_DIR=/tmp/localstack/data
